version: '3'
services:
  web:
    image: "cleborys/cakeclub:latest"
    ports:
      - "127.0.0.1:8000:5000"
    env_file:
      - web-variables.env
    environment:
      DATABASE_URL: postgres://cakelover:cakelover@database/cakelover
    depends_on:
      - database

  database:
    image: "postgres:12"
    environment:
      POSTGRES_USER: cakelover
      POSTGRES_PASSWORD: cakelover
